### ISSUE TITLE
hex_to_rgb: invalid hex_str: normal

### ISSUE THREAD

**Issue by aspeddro** [mvllow/modes.nvim#1]
modes.nvim not working.

![image](https://user-images.githubusercontent.com/16160544/128041436-2ff5d463-a565-429a-b984-64f4b0eed1f2.png)

My config:

```
--- init.lua
vim.o.cursorline = true
```

```lua
-- modes.lua
require('modes').setup({
  colors = {
    copy = "#f5c359",
    delete = "#c75c6a",
    insert = "#78ccc5",
    visual = "#9745be",
  },
  line_opacity = 0.9
})
```
```
nvim --version
NVIM v0.6.0-dev+43-g02bf251bb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Great package!!!

**Comment by mvllow** [comment]
Thanks for report! I noticed this issue if you were to say set `colors.copy = 'blue'` or some other word because only hex's are supported but not sure where it's getting `normal` from in this case. Will look into it ☺️

**Comment by mvllow** [comment]
I was able to reproduce this with some default themes (eg. "blue" colorscheme) where some colors are set to words instead of hex values. Fixed those cases but if it is still broken for you please reopen and let me know which theme you're using and I'll investigate further :)

**Comment by aspeddro** [comment]
i'm using https://github.com/marko-cerovac/material.nvim

```lua
-- theme config
vim.g.material_style = 'darker'
vim.g.material_italic_comments = true
vim.g.material_italic_keywords = false
vim.g.material_italic_functions = false
vim.g.material_italic_variables = false
vim.g.material_contrast = true
vim.g.material_disable_background = true
vim.g.material_custom_colors = {
  black = "#1A1A1A",
  bg = "#1A1A1A"
}
vim.g.material_variable_color="#82AAFF"
require('material').set()

```

![image](https://user-images.githubusercontent.com/16160544/128054015-8493a41f-7f05-4862-bf17-f96a9b729299.png)

**Comment by mvllow** [comment]
Thanks for your theme config, it was the `vim.g.material_disable_background = true` that was causing issues

**Comment by aspeddro** [comment]
Fixed :hugs:
