### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mvllow** [mvllow/modes.nvim#26]
Usually when something is added or changed in modes, I test locally and push up. Unfortunately, issues arise almost every update due to how different everyone's environment is.

I would love to learn more about tests in lua, but also am unaware of what exactly to test. PR's are welcome and appreciated 😌

**Comment by treatybreaker** [comment]
I'll be playing around with testing... it's about time I really learn `lua` properly and `plenary` anyhow. If you want we can get a CI pipeline going as well, I am more used to CI/CD in gitlab, but I'm sure we can get a simple docker image and a pipeline here on github w/ actions.

**Comment by treatybreaker** [comment]
I have the basic workflow [here](https://github.com/treatybreaker/modes-testing). Using a `Makefile` via `make test`. Relying on plenary, so plenary is going to become a test requirement if I stick to plenary. If plenary sounds good, I'll keep going with it and get these tests built out 😃.

**Comment by mvllow** [comment]
Plenary should be fine – I see that used quite often 😌 Thank you for working on this!

**Comment by treatybreaker** [comment]
Yeah, no problem. I'll get cracking on it then with plenary.

**Comment by mvllow** [comment]
Closed via #27 😌
