### ISSUE TITLE
feature request: add support for signcolumn and foldcolumn highlights

### ISSUE THREAD

**Issue by budswa** [mvllow/modes.nvim#31]
Hi. It is now possible to set the highlight of the cursor line in the sign and fold column too with the highlight groups CursorLineSign and CursorLineFold. It would be nice if this plugin supported it.
Thanks xx

**Comment by fitrh** [comment]
Can you try [this branch](https://github.com/fitrh/modes.nvim/tree/feat/sign-fold-hl)? I don't know how to test it properly since I don't use `signcolumn` or `foldcolumn` in my daily workflow

**Comment by budswa** [comment]
Works as expected. Thank you. 

You should open a pull request
