### ISSUE TITLE
Colorscheme is not always respected

### ISSUE THREAD

**Issue by mvllow** [mvllow/modes.nvim#37]
After #36, Rosé Pine theme (dark variant) doesn't use the colorscheme's palette. Light mode works as expected.

Users can pin to `tag = v0.2.0` if using a theme that is affected by this.

**Comment by fitrh** [comment]
How to reproduce this bug?

**Comment by mvllow** [comment]
With this config...

```lua
use({
	'rose-pine/neovim',
	config = function()
		require('rose-pine').setup()
		vim.cmd('colorscheme rose-pine')
	end,
})
use({
	'mvllow/modes.nvim',
	config = function()
		require('modes').setup()
	end,
})
```

...Rosé Pine colours are applied when using the dawn variant, e.g. `:set background=light` on load. If background is set to dark on load (meaning neovim set background to dark because my system was in dark mode) Rosé Pine colours are not applied. Manually doing `:set background=dark` works as expected.

Hope that makes sense :)

**Comment by fitrh** [comment]
Hmm, does calling `vim.on_key` at the very end of `setup` did not solve this issue?
