### ISSUE TITLE
Cursorline changed to visual mode when using LSP goto functions

### ISSUE THREAD

**Issue by icyrainz** [mvllow/modes.nvim#42]
Let's say I'm in Normal mode, then when I use my hotkey to go definition of the symbol under my cursor (vim.lsp.buf.definition()), the cursor line changes to visual mode color even though it's normal mode. If I press ESC, then it goes back to normal mode color. 

I think other LSP functions are also affected by this too.

**Comment by fitrh** [comment]
Can you provide reproduction steps? I can't reproduce your issue with `CTRL-]` or `god`, my `vim.lsp.buf.definition` key map

**Comment by icyrainz** [comment]
I tried to record it here:
https://asciinema.org/a/wsae78BECGmJWgKOYOcsISeka

My keymap for vim.lsp.buf.definition is 'gd'.
When I press `gd` quickly, it remains in visual mode (purple).
When I gress `g` and wait a bit (which key shows up), and then press `d`, it correctly remains in Normal mode.

My dotfiles if you are interested to check other stuffs: https://github.com/icyrainz/.dotfiles/tree/master/nvim

**Comment by fitrh** [comment]
Can you try the latest (0.2.1) or upstream version? It seems you are using an old version of modes.nvim

**Comment by icyrainz** [comment]
Oh awesome. this is fixed in 0.2.1. I was following the install instruction that has the 0.2.0 tag. I think we should update the README. Appreciated you checking this.

**Comment by fitrh** [comment]
> I was following the install instruction that has the 0.2.0 tag. I think we should update the README

Sorry for that, I've rarely paid attention to the README, I am working on some bug fixes right now, I'll make sure to update the README to reflect all the changes so far after that
