### ISSUE TITLE
Setting `set_number=false` still apply the color

### ISSUE THREAD

**Issue by DeeGeeMan** [mvllow/modes.nvim#44]
If I set the `set_number=true` it will still apply the color the number section in nvim for delete and insert modes.

**Comment by fitrh** [comment]
Thank you for reporting, I think I missed it during #30, #45 should fix it

**Comment by MKrbm** [comment]
I think set_cursor also work inappropriately.
Thank you.

![image](https://github.com/mvllow/modes.nvim/assets/57752203/3bc1e2ee-9f9b-4e9f-9cbd-859160a2ac56)

**Comment by fitrh** [comment]
@MKrbm what terminal emulator are you using? It depends on the terminal emulator

**Comment by MKrbm** [comment]
I was using PowerShell.

**Comment by fitrh** [comment]
@MKrbm yes, windows terminal does not support changing `'guicursor'`, https://vi.stackexchange.com/questions/28092/set-guicursor-has-no-effect-in-vim-on-windows
