### ISSUE TITLE
Add extend cursorline option

### ISSUE THREAD

**Issue by mvllow** [mvllow/modes.nvim#53]
I'd like to add an option not extend the cursorline in certain modes behind the line number and sign column. Currently, the cursorline is not extended when in Normal mode but is extended for other modes. Perhaps after this option is added we may want to extend the cursorline in Normal mode when extend is true.

**Comment by fitrh** [comment]
Can this be achieved by configuring the (undocumented) `Modes{Mode}CursorLineNr`/ `Modes{Mode}CursorLineSign` highlight groups?
