### ISSUE TITLE
This plugin breaks `NvChad/ui`

### ISSUE THREAD

**Issue by kamack38** [mvllow/modes.nvim#63]
This plugin breaks the *Colorify* part of the `NvChad/ui` plugin. After changing modes, the colour highlights are cleared.

Right after entering a file:
![image](https://github.com/user-attachments/assets/72349ff5-49cc-4d7e-a579-42a4c30fbf2c)

After changing current mode to 'insert':
![image](https://github.com/user-attachments/assets/e71bbca2-aceb-4ffe-9e32-95a226d3d3c3)

**Comment by kamack38** [comment]
This is no longer the case in the newest versions of `NvChad/ui`.

**Comment by mvllow** [comment]
Thank you for updating the issue, glad it’s no longer a problem ☺️
