### ISSUE TITLE
E5113 Error while calling lua chunkattempt to index local 'opts'

### ISSUE THREAD

**Issue by piersolenski** [mvllow/modes.nvim#8]
After the most recent update I've started getting the following error when trying to start Neovim:

```
E5113: Error while calling lua chunk: ~/.vim/plugged/modes.nvim/lua/modes/init.lua:127: attempt to index local 'opts'
 (a nil value)
```

Plz halp!

**Comment by mvllow** [comment]
Hmm I'm noticing this too, I've been away for the past two weeks and accepted a few PR's. I'll have to dig in and see what the issue is

**Comment by mvllow** [comment]
Manually passing the default config (replacing any values with your own preferences) seems to be a workaround for the time being!

```lua
require('modes').setup({
    colors = {
        copy = '#f5c359',
        delete = '#c75c6a',
        insert = '#78ccc5',
        visual = '#9745be',
    },
    line_opacity = 0.15,
    focus_only = false,
})
```
